export const ADD_NEW_ORBITDEF = 'ADD_NEW_ORBITDEF';
export const DELETE_ORBITDEF = 'DELETE_ORBITDEF';

export const ORBIT_DEF_INPUT_CHANGE = 'ORBIT_DEF_INPUT_CHANGE';
export const LOAD_ORBIT_DEFS_SUCCESS = 'LOAD_ORBIT_DEFS_SUCCESS';

export const LOAD_APP_SETTINGS_SUCCESS = 'LOAD_APP_SETTINGS_SUCCESS';
export const TEST_ORBIT_DEF_ACTION = 'TEST_ORBIT_DEF_ACTION';
