export const ADD_NEW_ORBITDEF = 'ADD_NEW_ORBITDEF';
export const DELETE_ORBITDEF = 'DELETE_ORBITDEF';

export const ORBIT_DEF_INPUT_CHANGE = 'ORBIT_DEF_INPUT_CHANGE';
export const LOAD_ORBIT_DEFS_SUCCESS = 'LOAD_ORBIT_DEFS_SUCCESS';

export const LOAD_APP_SETTINGS_SUCCESS = 'LOAD_APP_SETTINGS_SUCCESS';
export const TEST_ORBIT_DEF_ACTION = 'TEST_ORBIT_DEF_ACTION';


export const TIME_CHANGE = 'TIME_CHANGE';
export const INTERVAL_CHANGE = 'INTERVAL_CHANGE';
export const CX_CHANGE = 'CX_CHANGE';
export const CY_CHANGE = 'CY_CHANGE';

export const STATE_CHANGE = 'STATE_CHANGE';
export const ORBIT_DEFS_CHANGE = 'ORBIT_DEFS_CHANGE';

export const TEST_ACTION = 'TEST_ACTION';
